# rpp (RK3326)
# RK3326 is 4x Cortex-A35, plain ARMv8-A. The flags inherited from the rgb30
# (RK3566: A55, armv8.2-a) let gcc emit instructions the A35 does not have.
ARCH = -mtune=cortex-a35 -march=armv8-a -O3
LIBS = -flto 
SDL = SDL2
